### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by flojo941** [olivernadj/toolbox#1]
Hey Olvernadj,
I would love to make your ruby-Solution to get the E-Mail adresses run. But actually I always get the error: **undefined method `[]' for nil:NilClass (NoMethodError)** You got an idea that could fix this problem?

Thanks in advance
Florin

**Comment by olivernadj** [comment]
Hi @flojo941 
Please check the token or channel/group id.

I may need to improve the error messages, but I wanted to keep the code as tiny as possible.

Cheers,
Oliver
