### ISSUE TITLE
Question - Other ways of obtaining token

### ISSUE THREAD

**Issue by i001962** [olivernadj/toolbox#2]
Nice idea. I noticed now Slack asks you to request the legacy token from an Admin. Is there any other way to obtain the legacy token without asking for it? (maybe in the browser console of their webapp?) My requests have gone ignored so far. Thanks again for the idea though.

**Comment by i001962** [comment]
Managed to find the Legacy API key in the community by inspecting the webpage and searching for API. Thanks for your inspiration. 

https://app.memphis.io/publish/mosaic/5be8b34cfc993a325603452f

**Comment by olivernadj** [comment]
Glad to hear that.

**Comment by clone95** [comment]
Sorry for the dumb question: can I retrieve user's data as a simple user? or do I  need to be admin ? thanks, Giacomo.

**Comment by olivernadj** [comment]
hi @clone95  yes, you can dump the user list as user.

**Comment by clone95** [comment]
It's giving me an error (I don't know Ruby)

this is the *command*

ruby scraper.rb -t
xoxs-114510210496-600369275188-601513157911-ca3c5133bb67b83dce3e4f686bbfa81f6b52783f43fca9da4aeb6ba33ad15923
-g C3DS7RW2J

and this is the* error*

Traceback (most recent call last): ciao.rb:20:in `<main>': undefined method
`[]' for nil:NilClass (NoMethodError)

This a Legacy Token I retrieved from the HTML as the previous user pointed.

any suggestions?

thanks, Giacomo

Il giorno ven 5 apr 2019 alle ore 12:31 Oliver Nadj <
notifications@github.com> ha scritto:

**Comment by olivernadj** [comment]
hi @clone95 

You may mixed up the group with channel. Use -c instead of -g.

WARNING: You've exposed your private token. Please revoke it ASAP and never share again.

**Comment by clone95** [comment]
nice thanks. Why in your opinion it doesn't take the email
[image: Capture.PNG]
 too?

Il giorno ven 5 apr 2019 alle ore 13:07 Oliver Nadj <
notifications@github.com> ha scritto:
